version: '3'

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
      depends_on:
        - mongodb


    mongodb:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ~/apps/mongo:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=azka
        - MONGO_INITDB_ROOT_PASSWORD=1415
